CREATE DATABASE MOVIE

CREATE SCHEMA MYMOVIE
GO

CREATE TABLE MYMOVIE.MOVIE
(
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TITLE NVARCHAR(50) NOT NULL,
  [YEAR] INT NOT NULL CHECK ([YEAR] > 0),
  [TIME] INT NOT NULL CHECK ([TIME] > 0),
  [LANGUAGE] NVARCHAR(50) NOT NULL,
  RELEASE_DATE DATE NOT NULL,
  RELEASE_COUNTRY NVARCHAR(50) NOT NULL
)

CREATE TABLE MYMOVIE.ACTOR
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 ACT_FNAME NVARCHAR(50) NOT NULL,
 ACR_LNAME NVARCHAR(50) NOT NULL,
 ACT_GENDER NVARCHAR(10) NOT NULL
)
CREATE TABLE MYMOVIE.DIRECTOR
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 DIR_FNAME NVARCHAR(50) NOT NULL,
 DIR_LNAME NVARCHAR(50) NOT NULL
)
CREATE TABLE MYMOVIE.GENERS
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 GEN_TITLE NVARCHAR(20) NOT NULL 
)

CREATE TABLE MYMOVIE.REVIEWER
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 REV_NAME NVARCHAR(50) NOT NULL
)
CREATE TABLE MYMOVIE.RATING
(
 MOV_ID INT FOREIGN KEY REFERENCES MYMOVIE.MOVIE(ID),
 REV_ID INT FOREIGN KEY REFERENCES MYMOVIE.REVIEWER(ID),
 REV_STARS INT CHECK (REV_STARS > 0),
 NUM_O_RATINGS INT NOT NULL CHECK(NUM_O_RATINGS > 0)
)
CREATE TABLE MYMOVIE.MOVIE_GENERS
(
 MOV_ID INT FOREIGN KEY REFERENCES MYMOVIE.MOVIE(ID),
 GEN_ID INT FOREIGN KEY REFERENCES MYMOVIE.GENERS(ID)
)
CREATE TABLE MYMOVIE.MOVIE_DIRECTION
(
 MOV_ID INT FOREIGN KEY REFERENCES MYMOVIE.MOVIE(ID),
 DIR_ID INT FOREIGN KEY REFERENCES MYMOVIE.DIRECTOR(ID)
)
CREATE TABLE MYMOVIE.MOVIE_CAST
(
 MOV_ID INT FOREIGN KEY REFERENCES MYMOVIE.MOVIE(ID),
 ACT_ID INT FOREIGN KEY REFERENCES MYMOVIE.ACTOR(ID),
 [ROLE] NVARCHAR(30) NOT NULL
)

